name: publish_binaries

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the release'
        required: true

jobs:
  publish:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download ZIP from private release (via GitHub API)
        run: |
          set -e
          OWNER="${{ secrets.PRIVATE_REPO_OWNER }}"
          REPO="${{ secrets.PRIVATE_REPO_NAME }}"
          VERSION="${{ github.event.inputs.version }}"
          ZIP_NAME="Shared-${VERSION}.zip"
          API_URL="https://api.github.com/repos/${OWNER}/${REPO}/releases/tags/${VERSION}"
          echo "Fetching release info for tag: $VERSION"
          response=$(curl -s -H "Authorization: token ${{ secrets.REPO_READ_TOKEN }}" "$API_URL")
          # Extract asset download URL
          download_url=$(echo "$response" | jq -r ".assets[] | select(.name == \"$ZIP_NAME\") | .url")
          if [ -z "$download_url" ] || [ "$download_url" == "null" ]; then
            echo "::error::Asset $ZIP_NAME not found in release $VERSION"
            exit 1
          fi
          echo "Downloading from $download_url"
          curl -L \
            -H "Authorization: token ${{ secrets.REPO_READ_TOKEN }}" \
            -H "Accept: application/octet-stream" \
            "$download_url" -o "$ZIP_NAME"
          echo "ZIP_FILE=$ZIP_NAME" >> "$GITHUB_ENV"

      - name: Generate Checksum
        run: |
          CHECKSUM=$(shasum -a 256 ${{ env.ZIP_FILE }} | awk '{print $1}')
          echo "CHECKSUM=$CHECKSUM" >> "$GITHUB_ENV"

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_READ_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
          body: |
            プライベートリポジトリから公開されたバイナリです。
            Checksum (SHA256): ${{ env.CHECKSUM }}
          draft: false
          prerelease: false

      - name: Upload ZIP to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_READ_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.ZIP_FILE }}
          asset_name: ${{ env.ZIP_FILE }}
          asset_content_type: application/zip
